collections:
  - name: "productos"
    label: "Productos"
    folder: "productos"
    create: true
    format: "json"
    extension: "json"
    fields:
      - { label: "Nombre", name: "nombre", widget: "string" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Precio", name: "precio", widget: "string" }
      - { label: "Imagen", name: "imagen", widget: "image" }
